# Generated by Django 5.2.8 on 2025-11-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('año_fabricacion', models.IntegerField()),
                ('capacidad_pasajeros', models.IntegerField()),
                ('numero_chasis', models.CharField(max_length=30, unique=True)),
                ('numero_motor', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('soat', 'SOAT'), ('rec', 'REC'), ('matricula', 'Matrícula'), ('revision', 'Revisión Técnica'), ('otro', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='flota.bus')),
            ],
            options={
                'verbose_name': 'Documento Vehículo',
                'verbose_name_plural': 'Documentos Vehículos',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('mecanico', 'Mecánico'), ('electrico', 'Eléctrico'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_mantenimiento', models.DateField()),
                ('kilometraje', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taller', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='flota.bus')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_mantenimiento'],
            },
        ),
    ]
