# Generated by Django 5.2.8 on 2025-11-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField()),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pasajeros_confirmados', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='flota.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='core.conductor')),
                ('lugar_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='core.lugar')),
                ('lugar_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='core.lugar')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
