# Generated by Django 5.2.8 on 2025-11-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peajes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ganancia_neta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Costo Viaje',
                'verbose_name_plural': 'Costos Viajes',
            },
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peajes', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Peaje',
                'verbose_name_plural': 'Peajes',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
